apiVersion: v2
name: lighthouse
description: An open-source Ethereum 2.0 client, written in Rust
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: skylenet
    email: rafael@skyle.net
